### ISSUE TITLE
Basic annotation behaviour

### ISSUE THREAD

**Issue by CleonWong** [CleonWong/screenshot-app#37]
_Note that this Issue only deals with the logic of annotations, not the UI design._

### Acceptance Criteria
1. When there is no annotation, set all-round margins to `10%` of the **longer** side. This will be the minimum margin, i.e. Regardless of annotation, the margin on any side will not be smaller than this.
    - E.g. If uploaded image is `W: 400px` and `H: 100px`, all-round margins should be `400px * 0.1 = 40px`
2. For annotation on **portrait** and **square** images, refer to second image below.
3. For annotation on **landscape** images, refer to third image below.

### Screenshots
<img width="954" alt="image" src="https://user-images.githubusercontent.com/54378247/234443848-3e0958c1-b5bb-495e-8f57-7980a778143f.png">

![Acceptance Criteria - Annotation for portrait and square](https://user-images.githubusercontent.com/54378247/234524998-93879386-2bda-4fd0-8c20-685b6d3e21c9.png)

![Acceptance Criteria - Annotation for landscape](https://user-images.githubusercontent.com/54378247/234535495-2ba00426-7646-4119-a90b-439dd3a0a5d0.png)

**Comment by billythedummy** [comment]
closed by #40
